services:
  metube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: latest
    container_name: metube
    ports:
      - "8081:8081"
    volumes:
      - ./downloads:/downloads
    environment:
      - UID=1000
      - GID=1000
      - UMASK=022
      - DOWNLOAD_DIR=/downloads
      - STATE_DIR=/downloads/.metube
      - TEMP_DIR=/downloads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  downloads:
    driver: local
